global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'catalog-service'
    scrape_interval: 5s
    metrics_path: /metrics  # O FastAPI precisa ter endpoint de m√©tricas (veremos depois)
    static_configs:
      - targets: ['catalog-svc:80'] # Nome do Service no K8s

  - job_name: 'order-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['order-svc:80']
