global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Futuramente, descomente e ajuste para monitorar seus servi√ßos
  # - job_name: 'catalog-service'
  #   static_configs:
  #     - targets: ['catalog:8000']
  
  # - job_name: 'order-service'
  #   static_configs:
  #     - targets: ['order-service:8002']

