apiVersion: v1
kind: Secret
metadata:
  name: catalog-secrets
type: Opaque
stringData:
  # A conex√£o interna do cluster.
  # Usuario: admin | Senha: senha_secreta_123 | Host: postgres-svc | Banco: catalog_db
  DATABASE_URL: "postgresql://admin:senha_secreta_123@postgres-svc:5432/catalog_db"